//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patient_Registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pat_registration
    {
        public int p_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public Nullable<decimal> phno { get; set; }
    }
}
